Empty tuple
B-Lang-org/bsc pull request #269
Opened 2020-10-20 20:56 UTC by nanavati

A minor cleanup to make a struct with no fields properly in IConv (rather than making an undefined value that's never used).

This means we can get rid of a workaround for PrimMakeUndefined in Deriving and a different one for undefined interfaces in IExpand and, most importantly, unblocks implementing PrimMakeUndefined with generics.

2020-10-21 23:52 UTC, quark17 requested changes
Any idea why IExpand was using a don't-care?  Was there some reason for it in the past that is no longer a reason now?

This passes the testsuite, so I see no current reason to not do it. (Some `bsc.typechecker` tests that compare the ISyntax dump fail and will need to be updated to account for this change in the representation, but that's fine.)

If the two places I've commented can be resolved, I'd be happy to merge this.  Thanks!

2020-10-21 23:52 UTC, quark17 commented on src/comp/bsc.hs
> +    iPCheck flags symt imod "internal"
Can you explain this edit?  Was it intended to be included in this PR?

The effect of this change is (1) to remove the time taken in `iPCheck` from the time reported for the stage (by `dump`) and (2) to allow dumping `imod` even if `iPCheck` fails.  Both of these are reasonable things to want -- I assume that this edit was to help in debugging.  However, this edit is only changing one place -- while every other call to `iPCheck`, `iMCheck`, and `aCheck` is still being done before the associated call to `dump`.  That suggests to me that this might have been an edit during debugging that wasn't intended to be checked in?

2020-10-21 23:52 UTC, quark17 commented on src/comp/IConv.hs
> +iConvE errh flags r env pvs (CStructT ct []) = con
I wonder if this arm of `iConvE` could be unified with the next arm (for `CStructT` with non-empty `fs`).  It seems like they both produce the same `con` and then the non-empty arm just does the further step of wrapping it with `iAps con [] fs'`.  A single arm for all `CStruct` could avoid duplicating the code for `con`?

2020-10-22 03:58 UTC, nanavati commented on src/comp/bsc.hs
> +    iPCheck flags symt imod "internal"
I did initially change it for debugging, but the new version was so much easier to understand that I thought it was worth keeping. I think that's partially because it's IConv (where we previously didn't have any ISyntax to look at if things go wrong). I'm not opposed to making the change more generally, but I think this particular case is a bigger deal than the others.

2020-10-22 04:02 UTC, nanavati commented on src/comp/IConv.hs
> +iConvE errh flags r env pvs (CStructT ct []) = con
While they're conceptually doing something quite similar, I think the details are very different.

Once there are fields, you need to look in the symbol table to understand the field type (and then reconcile it with the concrete types you have). That's a whole host of complications that don't come up in the field-free case (which was still tricky to figure out in its own way).

2020-10-22 04:08 UTC, nanavati commented
> Any idea why IExpand was using a don't-care? Was there some reason for it in the past that is no longer a reason now?

I think the reason was purely that making the right ICTuple for the field-free case is tricky. While is cleaner, it took Lucas and I several tries to figure it out. We wouldn't have bothered except for the impact on generically implementing PrimMakeUndefined (which, beyond the cleanup, helps us understand the limits of generics).

2020-10-26 05:45 UTC, merged